name: waslaapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for good coding practices.
  flutter_lints: ^6.0.0

# The following section is specific to Flutter.
flutter:

  # Ensures that the Material Icons font is included.
  uses-material-design: true

  # Assets used in the application.
  assets:
    - assets/images/

  # To add custom fonts, use this example:
  #
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
